# Generated by Django 3.0.8 on 2020-09-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0002_remove_candidates_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
